create role R_SYS_JUNTA_MEDIC;

grant CREATE SEQUENCE to R_SYS_JUNTA_MEDIC;
grant CREATE VIEW to R_SYS_JUNTA_MEDIC;
grant CREATE TABLE to R_SYS_JUNTA_MEDIC;
grant CREATE TRIGGER to R_SYS_JUNTA_MEDIC;
grant CREATE PROCEDURE to R_SYS_JUNTA_MEDIC;
grant CREATE INDEXTYPE to R_SYS_JUNTA_MEDIC;
grant CREATE OPERATOR to R_SYS_JUNTA_MEDIC;
grant CREATE TYPE to R_SYS_JUNTA_MEDIC;