INSERT INTO PARAMETRO
(ID, NOME, DM_PARAM_TIPO_VALOR_ID, ENDERECO_SERVICO, VALOR_STRING, VALOR_DATE, VALOR_NUMBER, VALOR_CLOB, EXPLICACAO, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, VALOR_JSON, ENDERECO_SERVICO_TIPO, PARAMETRO_ADMINISTRATIVO)
VALUES(14, 'textos_prontos_tela_de_lembretes', 29, NULL, NULL, NULL, NULL, 'Configure as frases na tela de parametros;Frase Padrão', 'Informe as frases, utilize ponto e virgula para separar as frases', NULL, NULL, NULL, NULL, NULL, NULL, 0);

INSERT INTO PARAMETRO
(ID, NOME, DM_PARAM_TIPO_VALOR_ID, ENDERECO_SERVICO, VALOR_STRING, VALOR_DATE, VALOR_NUMBER, VALOR_CLOB, EXPLICACAO, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY, VALOR_JSON, ENDERECO_SERVICO_TIPO, PARAMETRO_ADMINISTRATIVO)
VALUES(15, 'texto_fixo_tela_de_lembretes', 29, NULL, NULL, NULL, NULL, 'Texto Fixo', 'Texto pronto padrão para já vir preenchido', NULL, NULL, NULL, NULL, NULL, NULL, 0);
