CREATE TABLE DESEMPATADOR_AREA_ATUACAO (
	ID NUMBER(18) NOT NULL, 
	DESEMPATADOR_ID NUMBER(18) NOT NULL, 
	AREA_ATUACAO_ID NUMBER(18) NOT NULL, 
	DATA_INATIVACAO DATE,
	CREATED_AT DATE, 
	CREATED_BY NUMBER(18), 
	UPDATED_AT DATE, 
	UPDATED_BY NUMBER(18) 
);

ALTER TABLE DESEMPATADOR_AREA_ATUACAO
    ADD CONSTRAINT DESEMPATADOR_AREA_ATUACAO_PK
        PRIMARY KEY (ID);
		
ALTER TABLE DESEMPATADOR_AREA_ATUACAO 
	ADD CONSTRAINT DESEMPATADOR_AREA_ATUACAO_UK 
		UNIQUE (DESEMPATADOR_ID, AREA_ATUACAO_ID);

ALTER TABLE DESEMPATADOR_AREA_ATUACAO
    ADD CONSTRAINT DESEMPATADOR_AREA_ATUACAO_DESEMPATADOR_FK
        FOREIGN KEY (DESEMPATADOR_ID) REFERENCES DESEMPATADOR (ID);
		
ALTER TABLE DESEMPATADOR_AREA_ATUACAO
    ADD CONSTRAINT DESEMPATADOR_AREA_ATUACAO_AREA_ATUACAO_FK
        FOREIGN KEY (AREA_ATUACAO_ID) REFERENCES AREA_ATUACAO (ID);
		
ALTER TABLE DESEMPATADOR_AREA_ATUACAO 
	ADD CONSTRAINT DESEMPATADOR_AREA_ATUACAO_CREATED_BY_FK 
		FOREIGN KEY (CREATED_BY) REFERENCES USUARIO (ID);
  
ALTER TABLE DESEMPATADOR_AREA_ATUACAO 
	ADD CONSTRAINT DESEMPATADOR_AREA_ATUACAO_UPDATED_BY_FK 
		FOREIGN KEY (UPDATED_BY) REFERENCES USUARIO (ID);

CREATE SEQUENCE S_DESEMPATADOR_AREA_ATUACAO MINVALUE 1 MAXVALUE 999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE ORDER;
