CREATE TABLE processo (
    id                            NUMBER(18) NOT NULL,
    beneficiario_id               NUMBER(18) NOT NULL,
    profissional_assistente_id    NUMBER(18) NOT NULL,
    auditor_id                    NUMBER(18) NOT NULL,
    consultor_id                  NUMBER(18) NOT NULL,
    desempatador_id               NUMBER(18) NOT NULL,
    administrativo_fesc_ext_id    NUMBER(18),
    auditor_qualidade_ext_id      NUMBER(18),
    administrativo_operadora_id   NUMBER(18),
    numero_pedido_guia            NUMBER(18),
    operadora_contratante_id      NUMBER(18) NOT NULL,
    inicio_processo               DATE,
    contrato_id                   NUMBER(18) NOT NULL,
    conclusao_processo            DATE,
    data_criacao                  DATE,
    data_alteracao                DATE,
    data_solicitacao              DATE,
    prazo_final_ans               DATE,
    procedimento_realizado        NUMBER(1),
    possui_liminar                NUMBER(1),
    possui_nip                    NUMBER(1),
    plano_regulamentado           NUMBER(1),
    indicacao_clinica             VARCHAR2(500 CHAR),
    parecer_desempatador          VARCHAR2(4000 CHAR),
    parecer_desempatador_rascunho VARCHAR2(4000 CHAR),
    resumo_ao_beneficiario        VARCHAR2(4000 CHAR),
    parecer_carater_solicitacao   VARCHAR2(4000 CHAR),
    necessario_mat_fab_distrib    NUMBER(1),
    status_etapa_id               NUMBER(18) NOT NULL,
    pode_mat_outro_fab            NUMBER(1),
    data_cancelamento             DATE,
    justificativa_cancelamento    VARCHAR2(500 CHAR),
    avaliacao_trabalho            NUMBER(2),
    avaliacao_desempatador        NUMBER(1),
    cobrar_processo               NUMBER(1),
    documentacao_completa         NUMBER(1),
    classificacao_interna_id      NUMBER NOT NULL,
    operadora_origem_id           NUMBER(18) NOT NULL,
    operadora_solicitante_id      NUMBER(18) NOT NULL,
    created_at                    DATE,
    created_by                    NUMBER(18),
    updated_at                    DATE,
    updated_by                    NUMBER(18),
    dm_carater_atendimento_id     NUMBER(10),
    dm_motivo_cancel_processo_id  NUMBER(10),
    dm_cancelamento_motivado_id   NUMBER(10)
);

ALTER TABLE processo ADD CONSTRAINT processo_pk PRIMARY KEY ( id );

CREATE SEQUENCE s_processo
    MINVALUE 1 MAXVALUE 999999999999999999
        NOCACHE ORDER;
