ALTER TABLE LOG_AUDITORIA ADD TABELA_ID_TEMP VARCHAR2(20);

UPDATE LOG_AUDITORIA SET TABELA_ID_TEMP = TABELA_ID;

ALTER TABLE LOG_AUDITORIA DROP COLUMN TABELA_ID;

ALTER TABLE LOG_AUDITORIA RENAME COLUMN TABELA_ID_TEMP TO TABELA_ID;
