CREATE TABLE AREA_ATUACAO (
	ID NUMBER(18) NOT NULL,
	NOME VARCHAR2(120),
	ATIVO NUMBER(1),
	CREATED_AT  DATE,
    CREATED_BY  NUMBER(18),
    UPDATED_AT  DATE,
    UPDATED_BY  NUMBER(18)
);

ALTER TABLE AREA_ATUACAO
    ADD CONSTRAINT AREA_ATUACAO_PK
        PRIMARY KEY (ID);
		
ALTER TABLE AREA_ATUACAO 
	ADD CONSTRAINT AREA_ATUACAO_CREATED_BY_FK 
		FOREIGN KEY (CREATED_BY) REFERENCES USUARIO (ID);
  
ALTER TABLE AREA_ATUACAO 
	ADD CONSTRAINT AREA_ATUACAO_UPDATED_BY_FK 
		FOREIGN KEY (UPDATED_BY) REFERENCES USUARIO (ID);

create sequence S_AREA_ATUACAO minvalue 1 maxvalue 999999999999999999 start with 1 increment by 1 nocache order;