ALTER TABLE PROCESSO ADD DATA_PARECER DATE;
ALTER TABLE PROCESSO ADD DATA_REPROVACAO_OPERADORA DATE;
ALTER TABLE PROCESSO ADD FLUXO_PROCESSO_ID NUMBER(18);

ALTER TABLE processo
    ADD CONSTRAINT processo_fluxo_processo_fk FOREIGN KEY ( fluxo_processo_id )
        REFERENCES fluxo_processo ( id );
