CREATE TABLE DESEMPATADOR_PAGAMENTO (
	ID NUMBER(18) NOT NULL, 
	DESEMPATADOR_ID NUMBER(18) NOT NULL, 
	BANCO_ID NUMBER(18) NOT NULL, 
	DM_FORMA_PAGAMENTO_ID NUMBER(18) NOT NULL,
	VIGENCIA DATE NOT NULL,
	CPF_CNPJ VARCHAR2(17) NOT NULL,
	AGENCIA VARCHAR2(30) NOT NULL,
	CONTA_CORRENTE VARCHAR2(30) NOT NULL,
	CREATED_AT DATE, 
	CREATED_BY NUMBER(18), 
	UPDATED_AT DATE, 
	UPDATED_BY NUMBER(18) 
);

ALTER TABLE DESEMPATADOR_PAGAMENTO
    ADD CONSTRAINT DESEMPATADOR_PAGAMENTO_PK
        PRIMARY KEY (ID);
		
ALTER TABLE DESEMPATADOR_PAGAMENTO 
	ADD CONSTRAINT DESEMPATADOR_PAGAMENTO_UK 
		UNIQUE (DESEMPATADOR_ID, VIGENCIA);

ALTER TABLE DESEMPATADOR_PAGAMENTO
    ADD CONSTRAINT DESEMPATADOR_PAGAMENTO_DESEMPATADOR_FK
        FOREIGN KEY (DESEMPATADOR_ID) REFERENCES DESEMPATADOR (ID);
		
ALTER TABLE DESEMPATADOR_PAGAMENTO
    ADD CONSTRAINT DESEMPATADOR_PAGAMENTO_BANCO_FK
        FOREIGN KEY (BANCO_ID) REFERENCES BANCO (ID);
		
ALTER TABLE DESEMPATADOR_PAGAMENTO
    ADD CONSTRAINT DESEMPATADOR_PAGAMENTO_DM_FORMA_PAGAMENTO_FK
        FOREIGN KEY (DM_FORMA_PAGAMENTO_ID) REFERENCES DOMINIO (ID);
		
ALTER TABLE DESEMPATADOR_PAGAMENTO 
	ADD CONSTRAINT DESEMPATADOR_PAGAMENTO_CREATED_BY_FK 
		FOREIGN KEY (CREATED_BY) REFERENCES USUARIO (ID);
  
ALTER TABLE DESEMPATADOR_PAGAMENTO 
	ADD CONSTRAINT DESEMPATADOR_PAGAMENTO_UPDATED_BY_FK 
		FOREIGN KEY (UPDATED_BY) REFERENCES USUARIO (ID);

CREATE SEQUENCE S_DESEMPATADOR_PAGAMENTO MINVALUE 1 MAXVALUE 999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE ORDER;
