ALTER TABLE PROCESSO_HIST_NOTIFICACAO DROP COLUMN CORPO;
ALTER TABLE PROCESSO_HIST_NOTIFICACAO ADD CORPO CLOB;
ALTER TABLE PROCESSO_HIST_NOTIFICACAO MODIFY ANEXO_ID NULL;
ALTER TABLE PROCESSO_HIST_NOTIFICACAO MODIFY CHAT_MENSAGEM_ID NULL;

ALTER TABLE PROCESSO_HIST_NOTIFICACAO DROP CONSTRAINT processo_hist_notif_fk;
ALTER TABLE PROCESSO_HIST_NOTIFICACAO DROP COLUMN PROCESSO_ETAPA_ID;

ALTER TABLE PROCESSO_HIST_NOTIFICACAO ADD STATUS_ETAPA_ID NUMBER(18);
ALTER TABLE PROCESSO_HIST_NOTIFICACAO
    ADD CONSTRAINT processo_hist_notif_status_fk FOREIGN KEY ( status_etapa_id )
        REFERENCES status_etapa ( id );

ALTER TABLE PROCESSO_HIST_NOTIFICACAO ADD COMPROVANTE_OBRIGATORIO NUMBER(1);
ALTER TABLE PROCESSO_HIST_NOTIFICACAO ADD COMPROVANTE_NOME VARCHAR2(110);
ALTER TABLE PROCESSO_HIST_NOTIFICACAO ADD REMETENTE_NOME VARCHAR2(200);
