INSERT INTO PERMISSAO VALUES (1, null, 'usuario_perfil:create', 'create', 'usuario_perfil', 'Permitir criação de perfil do usuário', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (2, null, 'usuario_perfil:edit', 'edit', 'usuario_perfil', 'Permitir edição de perfil do usuário', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (3, null, 'usuario_perfil:view', 'view', 'usuario_perfil', 'Permitir visualização do perfil do usuário', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (4, null, 'usuario_perfil:delete', 'delete', 'usuario_perfil', 'Permitir exclusão do perfil do usuário', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (5, null, 'permissionamento:create', 'create', 'permissionamento', 'Permitir criação de permissão', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (6, null, 'permissionamento:edit', 'edit', 'permissionamento', 'Permitir edição de permissão', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (7, null, 'permissionamento:view', 'view', 'permissionamento', 'Permitir visualização de permissão', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (8, null, 'permissionamento:delete', 'delete', 'permissionamento', 'Permitir exclusão de permissão', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (9, null, 'perfil:create', 'create', 'perfil', 'Permitir criação de perfil', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (10, null, 'perfil:edit', 'edit', 'perfil', 'Permitir edição de perfil', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (11, null, 'perfil:view', 'view', 'perfil', 'Permitir visualização de perfil', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (12, null, 'perfil:delete', 'delete', 'perfil', 'Permitir exclusão de perfil', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (13, null, 'perfil_permissionamento:create', 'create', 'perfil_permissionamento', 'Permitir criação de um perssionamento para um perfil', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (14, null, 'perfil_permissionamento:edit', 'edit', 'perfil_permissionamento', 'Permitir edição de um perssionamento para um perfil', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (15, null, 'perfil_permissionamento:view', 'view', 'perfil_permissionamento', 'Permitir visualização de um perssionamento para um perfil', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (16, null, 'perfil_permissionamento:delete', 'delete', 'perfil_permissionamento', 'Permitir exclusão de um perssionamento para um perfil', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (17, null, 'menu_processos:view', 'view', 'menu_processos', 'Permitir visualização de um processo do menu', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (18, 17, 'menu_processos.exibe_botao_novo_processo:view', 'view', 'exibe_botao_novo_processo', 'Permitir visualização do botão novo processo na tela de lista de processos', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (19, 17, 'menu_processos.exibe_icone_prioridade_grid:view', 'view', 'exibe_icone_prioridade_grid', 'Permitir visualização na grid ao lado do processo se o mesmo está priorizado', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (20, 17, 'menu_processos.edita_prioridade:edit', 'edit', 'edita_prioridade', 'Permitir trocar a prioridade', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (21, 17, 'menu_processos.edita_operadora_origem:edit', 'edit', 'edita_operadora_origem', 'Permitir trocar a operadora origem', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (22, 17, 'menu_processos.edita_desempatador:edit', 'edit', 'edita_desempatador', 'Permitir trocar o desempatador', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (23, 17, 'menu_processos.edita_data_parecer:edit', 'edit', 'edita_data_parecer', 'Permitir trocar a data do parecer', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (24, 17, 'menu_processos.edita_documentacao_completa:edit', 'edit', 'edita_documentacao_completa', 'Permitir editar o campo documentação completa', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (25, 17, 'menu_processos.edita_prazo_da_guia_legivel:edit', 'edit', 'edita_prazo_da_guia_legivel', 'Permitir editar o campo prazo da guia é legivel', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (26, 17, 'menu_processos.edita_classificacao_interna:edit', 'edit', 'edita_classificacao_interna', 'Permite editar o campo classificação interna', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (27, 17, 'menu_processos.edita_administrativo_fesc:edit', 'edit', 'edita_administrativo_fesc', 'Permite editar o campo administrativo FESC', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (28, 17, 'menu_processos.edita_auditor_qualidade_fesc:edit', 'edit', 'edita_auditor_qualidade_fesc', 'Permite editar o campo auditor qualidade FESC', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (29, 17, 'menu_processos.edita_comprovante:edit', 'edit', 'edita_comprovante', 'Permite anexar o comprovante', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (30, null, 'menu_cadastros:view', 'view', 'menu_cadastros', 'Permite visualizar opção de novo cadastro', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (31, 30, 'menu_cadastros.menu_desempatadores:view', 'view', 'menu_desempatadores', 'Permite visualizar opção de novo desempatador', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (32, 30, 'menu_cadastros.menu_operadoras:view', 'view', 'menu_operadoras', 'Permite visualizar opção de nova operadora', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (33, 30, 'menu_cadastros.menu_contratos:view', 'view', 'menu_contratos', 'Permite visualizar opção de nova contrato', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (34, 30, 'menu_cadastros.menu_equipe:view', 'view', 'menu_equipe', 'Permite visualizar opção de nova equipe', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (35, 30, 'menu_cadastros.menu_beneficiarios:view', 'view', 'menu_beneficiarios', 'Permite visualizar opção de nova beneficiário', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (36, 30, 'menu_cadastros.menu_profissionais_assistentes:view', 'view', 'menu_profissionais_assistentes', 'Permite visualizar opção de novo profissional assistente', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (37, null, 'menu_configuracoes:view', 'view', 'menu_configuracoes', 'Permite visualizar opção de configurações', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (38, 37, 'menu_configuracoes.menu_classificacao_interna:view', 'view', 'menu_classificacao_interna', 'Permite visualizar opção de nova classificação interna', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (39, 37, 'menu_configuracoes.menu_acoes:view', 'view', 'menu_acoes', 'Permite visualizar opção de nova ação', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (40, 37, 'menu_configuracoes.menu_calendario:view', 'view', 'menu_calendario', 'Permite visualizar opção de nova calendário', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (41, 37, 'menu_configuracoes.menu_classificacao_anexos:view', 'view', 'menu_classificacao_anexos', 'Permite visualizar opção de novo classificação de anexo', SYSDATE, 1, null, null);
INSERT INTO PERMISSAO VALUES (42, 37, 'menu_configuracoes.menu_fluxos_processo:view', 'view', 'menu_fluxos_processo', 'Permite visualizar opção de novo fluxo de processo', SYSDATE, 1, null, null);
