CREATE TABLE DESEMPATADOR_ESPECIALIDADE (
	ID NUMBER(18) NOT NULL,
	DESEMPATADOR_ID NUMBER(18) NOT NULL,
	ESPECIALIDADE_ID NUMBER(18) NOT NULL,
	CREATED_AT DATE,
	CREATED_BY NUMBER(18),
	UPDATED_AT DATE,
	UPDATED_BY NUMBER(18)
);

ALTER TABLE DESEMPATADOR_ESPECIALIDADE
    ADD CONSTRAINT DESEMPATADOR_ESPEC_PK
        PRIMARY KEY (ID);

ALTER TABLE DESEMPATADOR_ESPECIALIDADE
	ADD CONSTRAINT DESEMPATADOR_ESPECIALIDADE_UK
		UNIQUE (DESEMPATADOR_ID, ESPECIALIDADE_ID );

ALTER TABLE DESEMPATADOR_ESPECIALIDADE
    ADD CONSTRAINT DESEMPATADOR_ESPECIALIDADE_DESEMPATADOR_FK
        FOREIGN KEY (DESEMPATADOR_ID) REFERENCES DESEMPATADOR (ID);

ALTER TABLE DESEMPATADOR_ESPECIALIDADE
    ADD CONSTRAINT DESEMPATADOR_ESPECIALIDADE_ESPECIALIDADE_FK
        FOREIGN KEY (ESPECIALIDADE_ID) REFERENCES ESPECIALIDADE (ID);

ALTER TABLE DESEMPATADOR_ESPECIALIDADE
	ADD CONSTRAINT DESEMPATADOR_ESPECIALIDADE_CREATED_BY_FK
		FOREIGN KEY (CREATED_BY) REFERENCES USUARIO (ID);

ALTER TABLE DESEMPATADOR_ESPECIALIDADE
	ADD CONSTRAINT DESEMPATADOR_ESPECIALIDADE_UPDATED_BY_FK
		FOREIGN KEY (UPDATED_BY) REFERENCES USUARIO (ID);

CREATE SEQUENCE S_DESEMPATADOR_ESPECIALIDADE MINVALUE 1 MAXVALUE 999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE ORDER;
