ALTER TABLE NOTIFICACAO MODIFY (FORMA VARCHAR2(30));

INSERT INTO NOTIFICACAO (ID, FORMA) VALUES (S_NOTIFICACAO.NEXTVAL, 'WHATSAPP');
INSERT INTO NOTIFICACAO (ID, FORMA) VALUES (S_NOTIFICACAO.NEXTVAL, 'EMAIL');
INSERT INTO NOTIFICACAO (ID, FORMA) VALUES (S_NOTIFICACAO.NEXTVAL, 'ICARTAS');
