ALTER TABLE PROCESSO_HIST_NOTIFICACAO ADD modelo_carta_id NUMBER (18);

ALTER TABLE PROCESSO_HIST_NOTIFICACAO
    ADD CONSTRAINT PROCESSO_HIST_NOTIFICACAO_MODELO_CARTA_FK
        FOREIGN KEY (modelo_carta_id) REFERENCES MODELO_CARTA (ID);
