ALTER TABLE DESEMPATADOR ADD DATA_INCLUSAO DATE;

ALTER TABLE DESEMPATADOR ADD DATA_EXCLUSAO DATE;

ALTER TABLE DESEMPATADOR ADD MOTIVO_EXCLUSAO VARCHAR2(200);

ALTER TABLE DESEMPATADOR ADD INDICADO_POR VARCHAR2(200);

ALTER TABLE DESEMPATADOR ADD OBSERVACAO VARCHAR2(500);
