INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(1, 2, 5);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(2, 2, 1);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(3, 1, 5);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(4, 1, 2);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(5, 7, 5);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(6, 7, 6);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(7, 6, 5);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(8, 6, 7);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(9, 5, 1);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(10, 5, 2);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(11, 5, 6);

INSERT INTO CHAT_MENSAGEM_CONFIGURACAO (ID, PAPEL_LOGADO_ID, PAPEL_ID) VALUES(12, 5, 7);
