DELETE FROM LOG_AUDITORIA_ITEM LAI
WHERE LAI.LOG_AUDITORIA_ID in (SELECT L.ID FROM LOG_AUDITORIA L WHERE L.TABELA = 'classificacao_interna');

DELETE FROM LOG_AUDITORIA L
WHERE L.TABELA = 'classificacao_interna';
