CREATE TABLE BANCO (
	ID NUMBER(18) NOT NULL,
	CODIGO VARCHAR2(10) NOT NULL,
	NOME VARCHAR2(120) NOT NULL,
	DATA_INATIVACAO DATE, 
	CREATED_AT  DATE,
    CREATED_BY  NUMBER(18),
    UPDATED_AT  DATE,
    UPDATED_BY  NUMBER(18)
);

ALTER TABLE BANCO
    ADD CONSTRAINT BANCO_PK
        PRIMARY KEY (ID);
		
ALTER TABLE BANCO 
	ADD CONSTRAINT BANCO_CREATED_BY_FK 
		FOREIGN KEY (CREATED_BY) REFERENCES USUARIO (ID);
  
ALTER TABLE BANCO 
	ADD CONSTRAINT BANCO_UPDATED_BY_FK 
		FOREIGN KEY (UPDATED_BY) REFERENCES USUARIO (ID);

CREATE SEQUENCE S_BANCO MINVALUE 1 MAXVALUE 999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE ORDER;