CREATE TABLE PROCESSO_AREA_ATUACAO (
	ID NUMBER(18) NOT NULL, 
	PROCESSO_ID NUMBER(18) NOT NULL, 
	AREA_ATUACAO_ID NUMBER(18) NOT NULL, 
	CREATED_AT DATE, 
	CREATED_BY NUMBER(18), 
	UPDATED_AT DATE, 
	UPDATED_BY NUMBER(18) 
);

ALTER TABLE PROCESSO_AREA_ATUACAO
    ADD CONSTRAINT PROCESSO_AREA_ATUACAO_PK
        PRIMARY KEY (ID);
		
ALTER TABLE PROCESSO_AREA_ATUACAO
    ADD CONSTRAINT PROCESSO_AREA_ATUACAO_PROCESSO_FK
        FOREIGN KEY (PROCESSO_ID) REFERENCES PROCESSO (ID);
		
ALTER TABLE PROCESSO_AREA_ATUACAO
    ADD CONSTRAINT PROCESSO_AREA_ATUACAO_AREA_ATUACAO_FK
        FOREIGN KEY (AREA_ATUACAO_ID) REFERENCES AREA_ATUACAO (ID);
		
ALTER TABLE PROCESSO_AREA_ATUACAO 
	ADD CONSTRAINT PROCESSO_AREA_ATUACAO_CREATED_BY_FK 
		FOREIGN KEY (CREATED_BY) REFERENCES USUARIO (ID);
  
ALTER TABLE PROCESSO_AREA_ATUACAO 
	ADD CONSTRAINT PROCESSO_AREA_ATUACAO_UPDATED_BY_FK 
		FOREIGN KEY (UPDATED_BY) REFERENCES USUARIO (ID);

CREATE SEQUENCE S_PROCESSO_AREA_ATUACAO MINVALUE 1 MAXVALUE 999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE ORDER;
