ALTER TABLE PROCESSO MODIFY beneficiario_id NULL;
ALTER TABLE PROCESSO MODIFY profissional_assistente_id NULL;
ALTER TABLE PROCESSO MODIFY auditor_id NULL;
ALTER TABLE PROCESSO MODIFY operadora_contratante_id NULL;
ALTER TABLE PROCESSO MODIFY contrato_id NULL;
ALTER TABLE PROCESSO MODIFY operadora_origem_id NULL;
ALTER TABLE PROCESSO MODIFY operadora_solicitante_id NULL;
