INSERT INTO INFO_EDIT(ID, NOME) VALUES(1, 'Prioridade');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(2, 'Operadora Origem');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(3, 'Administrativo Operadora');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(4, 'Administrativo FESC');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(5, 'Auditor Qualidade FESC');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(6, 'Documentação Completa?');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(7, 'Data do Parecer');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(8, 'Prazo Da Guia É Legível');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(9, 'N° Pedido/Guia');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(10, 'Caráter Atendimento');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(11, 'Prazo Inicial(ANS)');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(12, 'Prazo Final(ANS)');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(13, 'Procedimento realizado');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(14, 'Possui Liminar');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(15, 'Possui Nip');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(16, 'Plano não é regulamentado');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(17, 'Indicação Clinica');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(18, 'Procedimento e itens');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(19, 'Área de Atuação');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(20, 'Beneficiário - Código');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(21, 'Beneficiário - Nome');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(22, 'Beneficiário - Sexo');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(23, 'Beneficiário - Data Nascimento');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(24, 'Beneficiário - E-mail');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(25, 'Beneficiário - Telefone Celular');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(26, 'Beneficiário - Endereço');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(27, 'Beneficiário - Observação');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(28, 'Profissional Assist. - CRM e UF');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(29, 'Profissional Assist. - CRO e UF');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(30, 'Profissional Assist. - Especialidades');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(31, 'Profissional Assist. - Nome');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(32, 'Profissional Assist. - E-mail');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(33, 'Profissional Assist. - Telefone Comercial');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(34, 'Profissional Assist. - Telefone Celular');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(35, 'Profissional Assist. - Endereço');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(36, 'Profissional Assist. - Observação');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(37, 'Auditor - CRM e UF');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(38, 'Auditor - CRO e UF');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(39, 'Auditor - Especialidades');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(40, 'Auditor - Nome');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(41, 'Auditor - Observação');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(42, 'Consultor - CRM e UF');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(43, 'Consultor - CRO e UF');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(44, 'Consultor - Especialidades');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(45, 'Consultor - Nome');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(46, 'Consultor - Observação');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(47, 'Profissional - Desempatador');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(48, 'Beneficiário - Telefone Fixo');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(49, 'Parecer do Auditor da Operadora');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(50, 'Parecer Visível a Operadora');
INSERT INTO INFO_EDIT(ID, NOME) VALUES(51, 'Número protocolo');

