CREATE TABLE CHAT_MENSAGEM_CONFIGURACAO(
	ID NUMBER(18) NOT NULL,
	PAPEL_LOGADO_ID NUMBER(18) NOT NULL,
	PAPEL_ID NUMBER(18) NOT NULL,
	CREATED_AT  date,
    CREATED_BY  number(18),
    UPDATED_AT  date,
    UPDATED_BY  number(18)
);

alter table CHAT_MENSAGEM_CONFIGURACAO
    add constraint chart_mensagem_configuracao_pk
        primary key (ID);
alter table CHAT_MENSAGEM_CONFIGURACAO
    add constraint CHAT_MENSAGEM_CONFIGURACAO_PAPEL_LOGADO_FK
        foreign key (PAPEL_LOGADO_ID) references PAPEL (ID);
alter table CHAT_MENSAGEM_CONFIGURACAO
    add constraint CHAT_MENSAGEM_CONFIGURACAO_PAPEL_FK
        foreign key (PAPEL_ID) references PAPEL (ID);

CREATE SEQUENCE S_CHAT_MENSAGEM_CONFIGURACAO MINVALUE 1 MAXVALUE 999999999999999999 START WITH 1 INCREMENT BY 1 NOCACHE ORDER;
