package com.juntamedica.processo.payload;

import com.juntamedica.anexo.payload.AnexoResponse;
import com.juntamedica.auditor.payload.AuditorResponse;
import com.juntamedica.beneficiario.payload.BeneficiarioResponse;
import com.juntamedica.consultor.payload.ConsultorResponse;
import com.juntamedica.contrato.payload.ContratoResponse;
import com.juntamedica.desempatador.payload.DesempatadorResponse;
import com.juntamedica.fluxoprocesso.payload.FluxoProcessoResponse;
import com.juntamedica.operadoralayout.payload.OperadoraLayoutResponse;
import com.juntamedica.processoareaatuacao.payload.ProcessoAreaAtuacaoResponse;
import com.juntamedica.processoitem.payload.ProcessoItemResponse;
import com.juntamedica.profissionalassistente.payload.ProfissionalAssistenteResponse;
import com.juntamedica.statusetapa.payload.StatusEtapaResponse;
import lombok.Builder;
import lombok.Data;
import java.time.LocalDateTime;
import java.util.List;

@Data
@Builder
public class ProcessoResponse {

    private Long id;
    private Boolean modoRascunho;
    private Boolean prioridade;
    private String numeroPedidoGuia;
    private Long dmCaraterAtendimentoId;
    private String dmCaraterAtendimentoDescricao;
    private LocalDateTime inicioProcesso;
    private ContratoResponse contrato;
    private LocalDateTime conclusaoProcesso;
    private LocalDateTime dataCriacao;
    private LocalDateTime dataAlteracao;
    private LocalDateTime dataSolicitacao;
    private LocalDateTime prazoInicialAns;
    private LocalDateTime prazoFinalAns;
    private LocalDateTime dataCancelamento;
    private Boolean procedimentoRealizado;
    private Boolean possuiLiminar;
    private Boolean possuiNip;
    private Boolean planoRegulamentado;
    private Boolean prazoGuiaLegivel;
    private String indicacaoClinica;
    private LocalDateTime dataParecer;
    private String parecerDesempatador;
    private String parecerDesempatadorRascunho;
    private String resumoAoBeneficiario;
    private String parecerCaraterSolicitacao;
    private Boolean necessarioMatFabDistrib;
    private Boolean podeMatOutroFab;
    private StatusEtapaResponse statusEtapa;
    private Long dmCancelamentoMotivadoId;
    private String dmCancelamentoMotivadoDescricao;
    private Long dmMotivoCancelProcessoId;
    private String dmMotivoCancelProcessoDescricao;
    private String justificativaOperadora;
    private String justificativaCancelamento;
    private Long avaliacaoTrabalho;
    private Long avaliacaoDesempatador;
    private Boolean documentacaoCompleta;
    private Long operadoraOrigemId;
    private String operadoraOrigemDescricao;
    private List<OperadoraLayoutResponse> operadoraOrigemLayouts;
    private Long operadoraSolicitanteId;
    private String operadoraSolicitanteDescricao;
    private List<ProcessoItemResponse> processoItemList;
    private List<AnexoResponse> anexoList;
    private FluxoProcessoResponse fluxoProcesso;
    private BeneficiarioResponse beneficiario;
    private ProfissionalAssistenteResponse profissionalAssistente;
    private AuditorResponse auditor;
    private ConsultorResponse consultor;
    private DesempatadorResponse desempatador;
    private Long administrativoFescExtId;
    private String administrativoFescExtDescricao;
    private Long auditorQualidadeExtId;
    private String auditorQualidadeExtDescricao;
    private Long administrativoOperadoraId;
    private String administrativoOperadoraDescricao;
    private Long operadoraContratanteId;
    private String operadoraContratanteDescricao;
    private String itensExclusivos;
    private String resumoParecerDesempatador;
    private String prazoSlaProcesso;
    private String prazoSlaProcessoEmDias;
    private String prazoSlaProcessoFormatado;
    private boolean prazoSlaProcessoEmAlerta;
    private String prazoSlaStatusProcesso;
    private String prazoSlaStatusProcessoFormatado;
    private boolean prazoSlaStatusProcessoEmAlerta;
    private LocalDateTime dataEstimadaConclusao;
    private Long dmCobrarProcessoId;
    private String dmCobrarProcessoDescricao;
    private Boolean parecerVisivelOperadora;
    private String numeroProtocolo;
    private List<ProcessoAreaAtuacaoResponse> areaAtuacaoList;
    private OperadoraLayoutResponse operadoraLayout;
}
